### ISSUE TITLE
Approve

### ISSUE THREAD

**Issue by ghost** [AvinashReddy3108/PaperplaneRemix#14]
`[22:49:05 / ERROR] telethon.client.updates: Unhandled exception on approve
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.8/site-packages/redis/connection.py", line 427, in read_from_socket
    bufflen = recv_into(self._sock, self._buffer)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/redis/_compat.py", line 75, in recv_into
    return sock.recv_into(*args, **kwargs)
TimeoutError: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.8/site-packages/telethon/client/updates.py", line 443, in _dispatch_update
    await callback(event)
  File "/home/ubuntu/ppr/userbot/plugins/pmpermit.py", line 215, in approve
    await update_db()
  File "/home/ubuntu/ppr/userbot/plugins/pmpermit.py", line 380, in update_db
    redis.set("approved:users", dill.dumps(approvedUsers))
  File "/home/ubuntu/.local/lib/python3.8/site-packages/redis/client.py", line 1801, in set
    return self.execute_command('SET', *pieces)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/redis/client.py", line 901, in execute_command
    return self.parse_response(conn, command_name, **options)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/redis/client.py", line 915, in parse_response
    response = connection.read_response()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/redis/connection.py", line 739, in read_response
    response = self._parser.read_response()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/redis/connection.py", line 470, in read_response
    self.read_from_socket()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/redis/connection.py", line 452, in read_from_socket
    raise ConnectionError("Error while reading from socket: %s" %
redis.exceptions.ConnectionError: Error while reading from socket: (110, 'Connection timed out')`

It is hard to approve somebody

**Comment by AvinashReddy3108** [comment]
> redis.exceptions.ConnectionError: Error while reading from socket: (110, 'Connection timed out')`

Make sure your redis endpoint and password is correct.

**Comment by ghost** [comment]
> > redis.exceptions.ConnectionError: Error while reading from socket: (110, 'Connection timed out')`
> 
> Make sure your redis endpoint and password is correct.

yes I am.

**Comment by AvinashReddy3108** [comment]
@Shiroikun Does it still not work?

**Comment by ghost** [comment]
> @Shiroikun Does it still not work?

sometimes yes sometimes no

**Comment by AvinashReddy3108** [comment]
@Shiroikun Maybe RedisLabs are undergoing routine maintenance.
